# Site settings
title: Coding to support my music habit
header-img: img/home-bg.png
email: christianavdm@gmail.com
copyright_name: christianavdm
description: > # this means to ignore newlines until "baseurl:"
  Learning a new creative field of web development
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  christianavdm
learn_profile: christianavdm
email_username: christianavdm@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
