# Site settings
author: Christiana Vandermale
title: Transition from Music to Coding 
header-img: img/home-bg.png
email: ryemrayne@gmail.com
copyright_name: Christiana Vandermale
description: > # this means to ignore newlines until "baseurl:"
  Learning a new creative field of web development
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  christianavdm

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
